name: MS Teams Deploy Card

on: [pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      # this is the new step
      - uses: toko-bifrost/ms-teams-deploy-card@master #  or "./" if in a local set-up
        if: always()
        with:
          github-token: ${{ github.token }}
          webhook-uri: ${{ secrets.MSTEAMS_WEBHOOK }}
          custom-facts: |
            - name: Custom Fact Name 1
              value: Custom Fact Value 1
            - name: Pull Request
              value: "http://example.com/${{ github.run_id }}"
          custom-actions: |
            - text: View PR
              url: "http://valid.uri.com"
            - text: View CI
              url: "http://example.com/${{ github.run_id }}"