name: Playwright API Checks
on: [workflow_dispatch, pull_request]
permissions:
  contents: write
  pages: write

jobs:
  e2e-tests:
    permissions:
      contents: read
      pages: write      
      id-token: write  
    timeout-minutes: 60
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.28.1-focal
    steps:
      - uses: actions/checkout@v3
        env:
          SLACK_BOT_USER_OAUTH_TOKEN: ${{ secrets.SLACK_BOT_USER_OAUTH_TOKEN }}
      - name: Install Dependencies
        run: npm ci
      - name: Run Playwright tests
        run: npm run test
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
      - name: Install rsync 📚
        if: always()
        run: |
          apt-get update && apt-get install -y rsync
     
      - name: Configure Pages
        uses: actions/configure-pages@v2
        if: always()
     
      - name: Setup Pages
        if: always()
        uses: actions/configure-pages@v2
     
      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'playwright-report/'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

  
  
  
  