name: Playwright API Checks
on: [workflow_dispatch, pull_request]
jobs:
  e2e-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.20.1-focal
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm ci
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
      - name: Install rsync 📚
        if: always()
        run: |
          apt-get update && apt-get install -y rsync
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.7
        if: always()
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: playwright-report # The folder the action should deploy.
